[package]
name = "lamp_srv"
version = "0.1.0"
authors = ["Ian Brault <ian@brault.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
